### ISSUE TITLE
Request-Reply using auto-generated queue names causes large Mule caches

### ISSUE THREAD

**Issue by mouldt** [mulesoft/mule-transport-amqp#96]
Hi,
we are on Mule v3.3.0 and using v3.3.0 of the transport. We perform a lot of request-reply messaging using the transport. Our message reciever is in a separate Mule instance and has a small memory footprint. What we see is the Mule and Spring object caches grow due to the auto-generated queue names that RabbitMQ creates to facilitate a request-reply mep. Each new queue must have a new DefaultOutboundEndpoint and this is cached in the ReplyToHandler and the Mule Registry and the Spring object cache. As such after some days we run out of memory.
We have changed the dispatcher to implement a queue name cache and only generate a new queue name if all queues in the cache are being used. Each cache entry has a flag to indicate if it is in use or not, all this cache is in the Dispatcher SEND action.
With the cache in place this clears our memory issue as our receiver will be able to reuse DefaultOutBoundendpoint instances from its cache rather than create a new one.
Not sure if this is still an issue on the later versions of mule, but i think its still a cleaner practice to try to re-use queue names rather then keep generating new ones.
Thanks

**Comment by vromero** [comment]
Mould I believe this is fixed in 3.6: https://repository.mulesoft.org/nexus/content/repositories/releases/org/mule/transports/mule-transport-amqp/3.6.0

I'm unsure how the 3.6 version would work on 3.3, I just tested up to 3.4. Could you give it a try?

**Comment by mouldt** [comment]
Hi,
Thanks for your response
We have tested later versions (although not 3.6) of the transport and these introduce other issues into our solution. I believe this is because we are also only on RabbitMQ v2.6.
I think our best approach would be to get our whole solution upgraded to more recent versions.

Thanks
Tony

**Comment by vromero** [comment]
Hello @mouldt, I'm closing this. If the problem persist on a later version please feel free to reopen.
